name: gateway
namespace: network-services
env: prod
image: wayruprod.azurecr.io/gateway
imageTag: latest
port: 4050
servicePort: 80 # used in ingress and service
host: network.wayru.tech # used in ingress
keycloakUrl: https://kc-1.wayru.tech
keycloakRealm: wayru
idpServiceUrl: http://idp-api.network-services.svc.cluster.local
mobileBackendUrl: http://mobile-backend.network-services.svc.cluster.local
healthPath: /health
cpuRequest: 200m
memoryRequest: 256Mi
cpuLimit: 500m
memoryLimit: 512Mi

azureCsiClientID: "a75a5340-f123-4f52-a0ec-b2c10bdaeeca"
azureKeyvaultTenantID: "9a2e7e82-78c3-4edd-932c-90f97a3da477"
keyvaultName: "wayruprod-gateway-kv"
