apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: {{ .Values.keyvaultName }}
    cloudName: ""
    tenantId: {{ .Values.azureKeyvaultTenantID }}
    {{- if eq .Values.env "local" }}
    useVMManagedIdentity: "false"
    {{- else }}
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.azureCsiClientID }}
    {{- end }}
    objects:  |
      array:
        - |
          objectName: keycloak-client-id
          objectType: secret
          objectVersion: ""
        - |
          objectName: keycloak-client-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: idp-service-key
          objectType: secret
          objectVersion: ""
  secretObjects:
    - secretName: {{ .Values.name }}
      type: Opaque
      data:
        - objectName: keycloak-client-id
          key: KEYCLOAK_CLIENT_ID
        - objectName: keycloak-client-secret
          key: KEYCLOAK_CLIENT_SECRET
        - objectName: idp-service-key
          key: IDP_SERVICE_KEY
