apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      volumes:
        - name: {{ .Values.name }}-csi-volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.name }}
            {{- if eq .Values.env "local" }}
            nodePublishSecretRef:
              name: azure-keyvault-principal
            {{- end }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}:{{ .Values.imageTag }}
          {{- if eq .Values.env "local" }}
          imagePullPolicy: IfNotPresent
          {{- else }}
          imagePullPolicy: Always
          {{- end }}
          env:
            - name: APP_ENV
              value: {{ .Values.env }}
            - name: PORT
              value: {{ .Values.port | quote }}
            - name: DASHBOARD_BACKEND_URL
              value: {{ .Values.dashboardBackendURL | quote }}
            - name: KEYCLOAK_URL
              value: {{ .Values.keycloakUrl | quote }}
            - name: KEYCLOAK_REALM
              value: {{ .Values.keycloakRealm | quote }}
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: KEYCLOAK_CLIENT_ID
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: KEYCLOAK_CLIENT_SECRET
            - name: IDP_SERVICE_URL
              value: {{ .Values.idpServiceUrl | quote }}
            - name: IDP_SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: IDP_SERVICE_KEY
            - name: MOBILE_BACKEND_URL
              value: {{ .Values.mobileBackendUrl | quote }}
            - name: MOBILE_BACKEND_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: MOBILE_BACKEND_KEY
            - name: DASHBOARD_BACKEND_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: DASHBOARD_BACKEND_KEY
            - name: DASHBOARD_BACKEND_ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: DASHBOARD_BACKEND_ADMIN_KEY
            - name: KEYCLOAK_ADMIN_REALM
              value: {{ .Values.keycloakAdminRealm | quote }}
            - name: KEYCLOAK_ADMIN_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: KEYCLOAK_ADMIN_CLIENT_ID
            - name: KEYCLOAK_ADMIN_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: KEYCLOAK_ADMIN_CLIENT_SECRET
          ports:
            - containerPort: {{ int .Values.port }}
              name: http
              protocol: TCP
          volumeMounts:
            - name: {{ .Values.name }}-csi-volume
              mountPath: /mnt/secrets
              readOnly: true
          resources:
            requests:
              cpu: {{ .Values.cpuRequest }}
              memory: {{ .Values.memoryRequest }}
            limits:
              cpu: {{ .Values.cpuLimit }}
              memory: {{ .Values.memoryLimit }}
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            httpGet:
              path: {{ .Values.healthPath }}
              port: {{ int .Values.port }}
              scheme: HTTP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            httpGet:
              path: {{ .Values.healthPath }}
              port: {{ int .Values.port }}
              scheme: HTTP
          startupProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            httpGet:
              path: {{ .Values.healthPath }}
              port: {{ int .Values.port }}
              scheme: HTTP
